apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
  # Access to custom resources
  - apiGroups: ["mysql.subat.cn"]
    resources: ["simplemysqls", "simplemysqlbackups"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Access to custom resource status
  - apiGroups: ["mysql.subat.cn"]
    resources: ["simplemysqls/status", "simplemysqlbackups/status"]
    verbs: ["get", "update", "patch"]
  
  # Access to core resources
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Access to apps resources
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Access to batch resources for jobs and cronjobs
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # For checking pods and creating events
  - apiGroups: [""]
    resources: ["pods/log", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  
  # For CRD management
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # For Kopf peerings
  - apiGroups: ["zalando.org"]
    resources: ["clusterkopfpeerings", "kopfpeerings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 