apiVersion: mysql.subat.cn/v1
kind: SimpleMySql
metadata:
  name: example-mysql-restore
  namespace: default
spec:
  database:
    name: app-restore
    password: root
  nodeSelector:
    subat.cn/region: xinjiang
  storage:
    size: 10Gi
    storageClass: xj-storage 
  callbackUrl: https://example.com/callback
  phpmyadmin:
    enabled: true
  restore:
    s3:
      bucket: "gitlab-storage"
      endpoint: "https://oss-xj.subat.cn"
      prefix: "mysql/backups"
      secretRef: "s3-credentials"
  backup:
    enabled: true
    schedule: "0 2 * * *"
    s3:
      bucket: "gitlab-storage"
      endpoint: "https://oss-xj.subat.cn"
      prefix: "mysql/backups"
      secretRef: "s3-credentials"
      keepDays: 7